name: CI Sécurité

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  security_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libxml2-dev libxslt-dev python3-dev build-essential

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies and security tools
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi
          pip install bandit==1.7.7 safety==2.3.5

      - name: Run Bandit
        run: |
          if [ -f bandit.yaml ]; then
            bandit -r . -c bandit.yaml -f json -o bandit-report.json || true
          else
            bandit -r . -f json -o bandit-report.json || true
          fi
          cat bandit-report.json

      - name: Run Safety
        run: |
          if [ -f requirements.txt ]; then
            safety check -r requirements.txt --full-report
          else
            echo "requirements.txt not found, skipping Safety check."
          fi

      - name: Upload Bandit report
        uses: actions/upload-artifact@v4
        with:
          name: bandit-report
          path: bandit-report.json
