name: CI Sécurité

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  security_scan:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Récupérer le code du dépôt
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Installer Python et les dépendances
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install bandit safety

      # 3️⃣ Analyse de sécurité avec Bandit
      - name: Run Bandit
        run: |
          bandit -r . -f json -o bandit-report.json
          cat bandit-report.json

      # 4️⃣ Analyse de sécurité des dépendances avec Safety
      - name: Run Safety
        run: |
          safety check -r requirements.txt --full-report
      - name: Upload Bandit report
        uses: actions/upload-artifact@v4
        with:
          name: bandit-report
          path: bandit-report.json
